import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { entries } from '../entries'
import _ from "lodash";

export default function Home() {




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />

      </Head>
      <h1 className="text-4xl">Homepage</h1>

    </div>
  )
}
